
SERIAL_DRIVER = vendor
SPLIT_KEYBOARD = yes

LAYER_LOCK_ENABLE = yes
CAPS_WORD_ENABLE = yes

CONSOLE_ENABLE = yes


#POINTING_DEVICE_ENABLE = yes
#POINTING_DEVICE_DRIVER = pmw3360
#MOUSEKEY_ENABLE = yes